[project]
name = "test-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bottle>=0.13.4",
    "discord-py>=2.5.2",
    "python-dotenv>=1.1.1",
]
